import type { Metadata } from 'next';
import PageHero from '@/components/sections/PageHero';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'Read the Suprfly Terms of Service governing your use of our AI auto-commenting platform.',
};

export default function TermsPage() {
  return (
    <>
      <PageHero
        breadcrumb={[{ label: 'Home', href: '/' }, { label: 'Terms of Service' }]}
        title="TERMS OF SERVICE"
        subtitle="Last updated: March 1, 2026"
      />

      <section className="py-24 md:py-36">
        <div className="max-w-3xl mx-auto px-6 prose prose-invert prose-headings:font-[var(--font-display)] prose-headings:uppercase prose-headings:tracking-tight prose-p:text-[#a1a1aa] prose-li:text-[#a1a1aa] prose-a:text-[#f59e0b] prose-a:no-underline hover:prose-a:underline prose-strong:text-white">
          <p>
            These Terms of Service (&quot;Terms&quot;) govern your access to and
            use of the Suprfly website, Chrome extension, and related services
            (collectively, the &quot;Service&quot;) provided by Suprfly
            (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By using the
            Service, you agree to these Terms in full.
          </p>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By creating an account or using any part of the Service, you confirm
            that you are at least 16 years old and have the legal capacity to
            enter into a binding agreement. If you are using the Service on
            behalf of an organisation, you represent that you have authority to
            bind that organisation to these Terms.
          </p>

          <h2>2. Description of the Service</h2>
          <p>
            Suprfly is an AI-powered platform that automatically generates and
            posts comments on LinkedIn and X on your behalf. The Service includes
            the Suprfly web dashboard, API, and Chrome extension for account
            connection.
          </p>

          <h2>3. Account Registration</h2>
          <p>
            You must provide accurate, complete information when creating an
            account and keep it up to date. You are responsible for maintaining
            the confidentiality of your login credentials and for all activity
            under your account. Notify us immediately at{' '}
            <a href="mailto:support@suprfly.io">support@suprfly.io</a> if you
            suspect unauthorised access.
          </p>

          <h2>4. Connected Platforms</h2>
          <p>
            When you connect LinkedIn or X through our Chrome extension, you
            authorise Suprfly to access your session cookies solely to post
            comments and interact with content on your behalf. You must comply
            with LinkedIn&apos;s and X&apos;s respective terms of service.
            Suprfly is not responsible for actions taken by those platforms,
            including account restrictions.
          </p>

          <h2>5. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for spam, harassment, hate speech, or illegal activity</li>
            <li>Attempt to reverse-engineer, decompile, or extract source code from the Service</li>
            <li>Share your account credentials or allow third parties to use your account</li>
            <li>Circumvent rate limits, usage caps, or other technical restrictions</li>
            <li>Use the Service to impersonate another person or entity</li>
            <li>Scrape, data-mine, or systematically download content from the Service</li>
          </ul>

          <h2>6. AI-Generated Content</h2>
          <p>
            Comments generated by Suprfly are created by artificial intelligence
            based on your configured persona and targeting rules. While we strive
            for high quality, you acknowledge that AI output may occasionally be
            inaccurate, inappropriate, or not aligned with your intent. You are
            solely responsible for all comments posted through your account and
            should review them regularly.
          </p>

          <h2>7. Payment and Billing</h2>
          <p>
            Paid plans are billed in advance on a monthly or annual basis via
            Stripe. Prices are listed on our pricing page and may change with 30
            days&apos; notice. All fees are non-refundable except as required by
            law or as described in our refund policy. Failure to pay may result
            in suspension or termination of your account.
          </p>

          <h2>8. Cancellation and Refunds</h2>
          <p>
            You may cancel your subscription at any time from your account
            settings. Cancellation takes effect at the end of the current billing
            period. We offer a full refund within 7 days of your first paid
            subscription if you are not satisfied. After 7 days, no refunds are
            provided for partial billing periods.
          </p>

          <h2>9. Intellectual Property</h2>
          <p>
            All content, software, trademarks, and other intellectual property
            within the Service are owned by Suprfly or our licensors. You retain
            ownership of any content you provide (e.g., persona descriptions,
            targeting keywords). By using the Service, you grant us a limited
            licence to use that content solely to operate and improve the Service.
          </p>

          <h2>10. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, Suprfly shall not be liable
            for any indirect, incidental, special, consequential, or punitive
            damages, including loss of profits, data, or business opportunities,
            arising from your use of the Service. Our total liability for any
            claim shall not exceed the amount you paid us in the 12 months
            preceding the claim.
          </p>

          <h2>11. Termination</h2>
          <p>
            We may suspend or terminate your account at any time for violation of
            these Terms, non-payment, or at our sole discretion with 30
            days&apos; notice. Upon termination, your right to use the Service
            ceases immediately. We will retain your data for 30 days after
            termination to allow for export, after which it will be permanently
            deleted.
          </p>

          <h2>12. Changes to These Terms</h2>
          <p>
            We may update these Terms from time to time. Material changes will be
            communicated via email or a prominent notice on the Service at least
            30 days before they take effect. Continued use of the Service after
            the effective date constitutes acceptance of the revised Terms.
          </p>

          <h2>13. Governing Law</h2>
          <p>
            These Terms are governed by and construed in accordance with the laws
            of the State of California, without regard to conflict-of-law
            principles. Any disputes arising under these Terms shall be resolved
            exclusively in the state or federal courts located in San Francisco
            County, California.
          </p>

          <h2>14. Contact</h2>
          <p>
            If you have questions about these Terms, please contact us at{' '}
            <a href="mailto:legal@suprfly.io">legal@suprfly.io</a> or write to
            Suprfly, 548 Market St, Suite 40122, San Francisco, CA 94104.
          </p>
        </div>
      </section>
    </>
  );
}
